# Generated by Django 5.0.6 on 2026-02-14 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('url', models.URLField(verbose_name='URL сайта')),
                ('site_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID сайта')),
                ('widget_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки виджета')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Рабочие часы')),
                ('auto_reply_enabled', models.BooleanField(default=False, verbose_name='Автоответ включён')),
                ('auto_reply_message', models.TextField(blank=True, verbose_name='Сообщение автоответа')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram Bot Token')),
                ('telegram_referral_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Реферальный код Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'ordering': ['-created_at'],
            },
        ),
    ]
