# Generated by Django 5.0.6 on 2026-04-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='Email-канал включён'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_imap_host',
            field=models.CharField(blank=True, default='imap.mail.ru', max_length=255, verbose_name='IMAP хост'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_imap_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP пароль'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_imap_port',
            field=models.PositiveIntegerField(default=993, verbose_name='IMAP порт'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_imap_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP логин'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_last_uid',
            field=models.CharField(blank=True, max_length=50, verbose_name='Последний обработанный UID'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_smtp_host',
            field=models.CharField(blank=True, default='smtp.mail.ru', max_length=255, verbose_name='SMTP хост'),
        ),
        migrations.AddField(
            model_name='site',
            name='email_smtp_port',
            field=models.PositiveIntegerField(default=465, verbose_name='SMTP порт'),
        ),
    ]
