# Generated by Django 5.0.6 on 2026-04-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('starter', 'Старт'), ('business', 'Бизнес'), ('enterprise', 'Корпоратив')], default='starter', max_length=20, verbose_name='Тариф'),
        ),
    ]
