# Generated by Django 5.0.6 on 2026-02-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='chat',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram User ID'),
        ),
    ]
