# Generated by Django 5.0.6 on 2026-04-27 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_telegram_chat_id_chat_telegram_user_id'),
        ('sites', '0003_site_email_enabled_site_email_imap_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='Message-ID последнего письма'),
        ),
        migrations.AddField(
            model_name='chat',
            name='email_subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='Тема письма'),
        ),
        migrations.AddField(
            model_name='chat',
            name='email_thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Thread-ID'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='channel',
            field=models.CharField(choices=[('widget', 'Виджет'), ('telegram', 'Telegram'), ('email', 'Email')], default='widget', max_length=10, verbose_name='Канал'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-updated_at'],
                'unique_together': {('site', 'email')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='chats.contact', verbose_name='Контакт'),
        ),
    ]
